### ISSUE TITLE
выгрузка параметров активного заказа в Детали

### ISSUE THREAD

**Issue by robespier** [robespier/indigo-client#6]
html-шаблон:
... ng-repeat="item in orders ... ng-click="setActiveOrder(item)"

контроллер:
$scope.order;
$scope.orders = Orders.all(current_day);
...
        $scope.setActiveOrder = function(item) {
            $scope.order = item;
            $location.path('/details');
        };

вопрос:
Какой синтаксис должен быть у item в setActiveOrder()?

**Comment by domelaz** [comment]
```html
<tr ng-repeat="item in orders ..." ng-click="setActiveOrder()">...</tr>
```
`ng-click` создаёт свой собственный `scope`
```JavaScript
$scope.setActiveOrder = function() {
    var order = this.item; // кликнутый ордер
    $scope.order = this.item; // передача ордера в "базовый" scope, который в контроллере Orders (если надо)
    $location.path('/details/' + ':' + order.field_with_id_role);
}
```
